#!/bin/bash
/home/gracedb.processor/users/ressick/SegDB2GraceDB/seglogic.py -v /home/gracedb.processor/users/ressick/SegDB2GraceDB/seglogic.ini >> /home/gracedb.processor/users/ressick/working/seglogic.out 
